@host = http://127.0.0.1:3000

###
GET {{host}} HTTP/1.1

//-----GET ALL-----

###
GET {{host}}/teacher HTTP/1.1
Accept: application/json
###

//---GET-ID---

GET {{host}}/profesores/2 HTTP/1.1
Accept: application/json

//------------AGREGAR------------------

###
POST {{host}}/profesores HTTP/1.1
Content-Type: application/json

{
    "id": 3,
  "nombre": "Jens",
  "especialidad": "Python"
}
###
POST {{host}}/profesores HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "nombre": "Julio",
    "especialidad": "Java"
}

//---------MODIFICAR--------

###
PUT {{host}}/profesores/4 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Yasmin",
    "especialidad": "C#"
}

//-------ELIMINAR-----

###
DELETE {{host}}/profesores/3 HTTP/1.1
Content-Type: application/json
###
DELETE {{host}}/profesores/1 HTTP/1.1
Content-Type: application/json


